#!/bin/bash

chown root:wheel /etc/MinimalHostsBlocker
chmod 755 /etc/MinimalHostsBlocker
chown root:wheel /etc/MinimalHostsBlocker/minimalhosts
chmod 644 /etc/MinimalHostsBlocker/minimalhosts
chown root:wheel /etc/MinimalHostsBlocker/defaulthosts
chmod 644 /etc/MinimalHostsBlocker/defaulthosts
echo "Overwriting hosts file..."
cp -a /etc/MinimalHostsBlocker/minimalhosts /etc/hosts
echo "Overwrite complete!"
chown root:wheel /etc/hosts
chmod 644 /etc/hosts
echo "Killing discoveryd..."
killall -9 discoveryd
echo "Should have died and restarted by now..."
echo "Deleting .git folder..."
rm -rf .git
echo ".git folder deleted!"
echo "Enjoy Minimal Hosts Blocker!"
echo "Please let me know if you find any ads or broken sites!"
exit 0
